#! /bin/ruby

# Accepts 4 arguments: icon for:
# * Charging
# * Full battery
# * Half battery
# * Empty battery
# and the icon font index for lemonbar

if ARGV.length != 5
  puts "Expecting 5 arguments"
  exit 1
end

CHARGING_ICON = ARGV[0]
FULL_ICON = ARGV[1]
HALF_ICON = ARGV[2]
EMPTY_ICON = ARGV[3]
INDEX = ARGV[4]

regex = /(\w+), (\d+)%(, (\d+):(\d+):(\d+))?/
out = `acpi -b`
regex.match out
status = $~[1]
percentage = $~[2].to_i
hours = $~[4]
minutes = $~[5]
icon = ""

if status == "Charging"
  icon = CHARGING_ICON
elsif percentage >= 50
  icon = FULL_ICON
elsif percentage < 50 and percentage >= 20
  icon = HALF_ICON
else
  icon = EMPTY_ICON
end

out = "%{T#{INDEX}}#{icon}%{T-} #{percentage.to_s}"
if hours != nil
  out += " (#{hours}:#{minutes})"
end

puts out
