#! /bin/bash -x

monitor_x=$(xrandr | grep "primary" | awk '{print $4}' | awk -F+ '{print $2}')
monitor_y=$(xrandr | grep "primary" | awk '{print $4}' | awk -F+ '{print $3}')
monitor_width=$(xrandr | grep "primary" | awk -F'[ x+]' '{print $4}')
monitor_height=$(xrandr | grep "primary" | awk -F'[ x+]' '{print $5}')
pad_x="50"
pad_y="30"
height="50"
in_pad="30"
font="-*-erusfont-medium-*-*-*-11-*-*-*-*-*-*-*"

color_summary="#71c2af"
color_bg="#1d2a30"
color_fg="#c27171"

sind -d -f '%s^%b' |\
  while read -r line; do
    summary=$(echo $line | awk -F^ '{print $1}')
    body=$(echo $line | awk -F^ '{print $2}')
    [ -n body ] && space=" "
    text_width=$(txtw -f $font "${summary}${body}")
    width=$((2 * in_pad + text_width))
    bar_opts="-g ${width}x${height}+$((monitor_x + monitor_width - pad_x - width))+$((monitor_y + monitor_height - pad_y - height)) -B $color_bg -f $font"
    (echo "%{c}%{F$color_summary}${summary}${space}%{F$color_fg}${body}"; sleep 3) | lemonbar ${bar_opts}
  done
