#!/usr/bin/env python
import re
import os

class Package:
    def __init__(self,name,size):
        self.name = name
        self.size = int(round(float(size)))
    def __repr__(self):
        return `self.size`+" "+self.name    
    def __cmp__(self,other):
        return cmp(other.size,self.size) #desc

paclist = []        

re_name = re.compile(r'Name\s*:\s*(\S+)')
