#! /bin/sh

. panel_icons

num_mon=$(bspc query -M | wc -l)

separator="%{F$COLOR_SEPARATOR}|%{F-}"

while read -r line ; do
  case $line in
    PS*)
      playing="%{A1:mpc toggle:}%{A2:urxvt -e /usr/bin/cava &:}%{A3:mpc stop:}%{A4:mpc next:}%{A5:mpc prev:}${line#??}%{A}%{A}%{A}%{A}%{A}"
      ;;
    S*)
      # clock output
      time=" ${line#?}"
      ;;
    T*)
      # xtitle output
      title=" %{T2}%{F$COLOR_TITLE}${line#?}%{F-}%{T-}"
      ;;
    B*)
      # battery output
      battery=" ${line#?}"
      ;;
    V*)
      # volume
      volume="%{A3:amixer sset Master toggle:}%{A4:amixer sset Master 5%+:}%{A5:amixer sset Master 5%-:}${line#?}%{A}%{A}%{A}"
      ;;
    W*)
      # bspwm internal state
      wm_infos=""
      IFS=':'
      set -- ${line#?}
      while [ $# -gt 0 ] ; do
        item=$1
        name="${item#?}"
        #name="$(icon $ICON_CLOCK)"
        name="%{A:bspc desktop -f $name:} ${name} %{A}"
        case $item in
          #M*)
          # # active monitor
          # if [ $num_mon -gt 1 ] ; then
          #   wm_infos="$wm_infos %{F$COLOR_ACTIVE_MONITOR_FG}%{B$COLOR_ACTIVE_MONITOR_BG} ${name} %{B-}%{F-}  "
          # fi
          # ;;
          #m*)
          # # inactive monitor
          # if [ $num_mon -gt 1 ] ; then
          #   wm_infos="$wm_infos %{F$COLOR_INACTIVE_MONITOR_FG}%{B$COLOR_INACTIVE_MONITOR_BG} ${name} %{B-}%{F-}  "
          # fi
          # ;;
          O*)
            # focused occupied desktop
            wm_infos="$wm_infos%{+u}${name}%{-u}"
            ;;
          F*)
            # focused free desktop
            wm_infos="$wm_infos%{+u}${name}%{-u}"
            ;;
          U*)
            # focused urgent desktop
            wm_infos="$wm_infos%{B$COLOR_URGENT}%{+u}${name}%{-u}%{B-}"
            ;;
          o*)
            # occupied desktop
            wm_infos="$wm_infos${name}"
            ;;
          f*)
            # free desktop
            wm_infos="$wm_infos${name}"
            ;;
          u*)
            # urgent desktop
            wm_infos="$wm_infos%{B$COLOR_URGENT}${name}%{B-}"
            ;;
          #L*)
          # # layout
          # wm_infos="$wm_infos  %{F$COLOR_LAYOUT_FG}%{B$COLOR_LAYOUT_BG} ${name} %{B-}%{F-}"
          # ;;
        esac
        shift
      done
      ;;
  esac
  echo -e "%{l}${wm_infos} $separator ${title}%{r}${battery} $separator ${volume} $separator $(icon $ICON_CLOCK)${time} $separator ${playing} "
done
