#! /bin/bash

PANEL_FIFO=/tmp/pamel-fifo
PANEL_HEIGHT=30
PANEL_WM_NAME="lemonbar"
#PANEL_FONT_FAMILY=-*-tamsynmod-medium-*-*-*-17-*-*-*-*-*-*-*
PANEL_FONT_FAMILY=-*-envypn-medium-*-*-*-13-*-*-*-*-*-*-*
PANEL_ICON_FONT_FAMILY=-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1
REFRESH_VOLUME=0.5
REFRESH_MUSIC=1
REFRESH_BATTERY=10
