#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# export TERM=xterm-256color
export TERM=xterm-256color
export EDITOR=nano
export VISUAL=vim
export PATH="$(ruby -e 'print Gem.user_dir')/bin:$PATH"

source ~/.dotfiles/base16-ocean.dark.sh
source "$HOME/.homesick/repos/homeshick/homeshick.sh"

# Vi mode
bindkey -v
export KEYTIMEOUT=1

# The Fuck is real
eval $(thefuck --alias)

fortune | lolcat

# Remove unnecessary packages
pclean() {
  sudo pacman -Rsn $(pacman -Qdtq)
}
