#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

source ~/crosssh.sh

# Customize to your needs...
#export TERM=xterm-256color
bindkey -v
export KEYTIMEOUT=1

# Set window title to "username@hostname: directory"
precmd () {print -Pn "\e]0;%n@%m: %~\a"}
