#!/bin/sh
#
# Listen for focus events and apply double border.
# Inspired by neeasade https://nixers.net/showthread.php?tid=1677&pid=15384#pid15384
# Work in progress. Do not use it.
#
# (c) 2016 Tudor Roman - wtfpl
#

inner="4"
outer="2"

focusedTint=80
normalTint=20

outerFocused="$(xrq '*.color0' | sed 's/\#/0x/')"
innerFocused="$(xrq '*.color6' | sed 's/\#/0x/')"
outerNormal="$(xrq '*.color0' | sed 's/\#/0x/')"
innerNormal="$(xrq '*.color8' | sed 's/\#/0x/')"

_chwb2() {
	local colorType="$1"
	local window="$2"


	if [ "$colorType" = "focused" ]; then
		local innerColor="$innerFocused"
		local outerColor="$outerFocused"
	else
		local innerColor="$innerNormal"
		local outerColor="$outerNormal"
	fi

	chwb2 -I $innerColor -O $outerColor -i $inner -o $outer $window
}

(while :; do _chwb2 focused `pfw`; sleep 0.1; done) &

wew -m 2097152 | \
while read -r line; do
	event="$(echo "$line" | cut -d':' -f1)"
	window="$(echo "$line" | cut -d':' -f2)"

	if [ "$event" -eq 9 ]; then
		colorType="focused"
	else
		colorType="normal"
	fi

	_chwb2 "$colorType" "$window"
done
