#!/bin/sh
#
# Listen for focus events and apply double border.
# Inspired by neeasade https://nixers.net/showthread.php?tid=1677&pid=15384#pid15384
# Work in progress. Do not use it.
#
# (c) 2016 Tudor Roman - wtfpl
#

inner="2"
outer="4"

inner="$(( BW / 2 ))"
outer="$(( BW - inner))"

focusedTint=80
normalTint=20

outerFocused="$(xrq '*.color4' | sed 's/\#/0x/')"
innerFocused=`colort -l $focusedTint "$outerFocused"`
outerNormal="$(xrq '*.color0' | sed 's/\#/0x/')"
innerNormal=`colort -l $normalTint "$outerNormal"`

_chwb2() {
	local colorType="$1"
	local window="$2"


	if [ "$colorType" = "focused" ]; then
		local innerColor="$innerFocused"
		local outerColor="$outerFocused"
	else
		local innerColor="$innerNormal"
		local outerColor="$outerNormal"
	fi

	chwb2 -I $innerColor -O $outerColor -i $inner -o $outer $window
}

wew -m 2097152 | \
while read -r line; do
	event="$(echo "$line" | cut -d':' -f1)"
	window="$(echo "$line" | cut -d':' -f2)"

	if [ "$event" -eq 9 ]; then
		colorType="focused"
	else
		colorType="normal"
	fi

	_chwb2 "$colorType" "$window"
done
