#! /bin/sh
#
# blur wallpaper if there are windows on the screen
# (c) tudurom 2016 - wtfpl
#

wew |\
while IFS=: read -r ev wid; do
    case $ev in
        16|18|19)
            if [ "$(lsw | wc -l)" -eq 0 ]; then
                wall-e
            else
                wall-e "${WALL_DIR}/blur/${WALL}"
            fi
            ;;
    esac
done
