#! /bin/dash
#
# puts a window in a given corner or in the middle of the screen
# (c) tudurom 2016 - wtfpl
#

. wmrc
. panelsrc

pfw="${2:-$(pfw)}"
root="$(lsw -r)"
screen_width="$(wattr w $root)"
screen_height="$(wattr h $root)"

border_width="$(wattr b $pfw)"
width="$(wattr w $pfw)"
height="$(wattr h $pfw)"

x=0
y=0

case $1 in
  tr)
    x=$(( screen_width - width - 2 * border_width - GENERAL_GAP ))
    y=$(( 2 * GENERAL_GAP + PANEL_STATUS_HEIGHT ))
    ;;
  bl)
    x=$GENERAL_GAP
    y=$(( screen_height - height - 2 * border_width - GENERAL_GAP ))
    ;;
  br)
    x=$(( screen_width - width - 2 * border_width - GENERAL_GAP ))
    y=$(( screen_height - height - 2 * border_width - GENERAL_GAP))
    ;;
  md)
    x=$(( screen_width / 2 - width /  2 - border_width ))
    y=$(( screen_height / 2 - height / 2 - border_width ))
esac

wtp $x $y $width $height $pfw

# vim: set ft=sh :
