#!/bin/sh

ppd=`ppd`
DISP_W=`dattr -w $ppd`
DISP_H=`dattr -h $ppd`
DISP_X=`dattr -x $ppd`
DISP_Y=`dattr -y $ppd`

GROOT=${GROOT:-/tmp/groaw}
GNUMBER=${GNUMBER:-6}

BAR_W="$(( $(txtw -f Siji " ") * GNUMBER + $(txtw -f terminal " ") * (GNUMBER - 1) ))"
BAR_H="$PANEL_STATUS_HEIGHT"
BAR_X="$(( (DISP_W - BAR_W) / 2 ))"
BAR_Y="$GENERAL_GAP"

BAR_BG="$(xrq '*.background')"
BAR_FG="$(xrq '*.foreground')"
BAR_UN="$(xrq '*.color9')"
BAR_FONT="$PANEL_FONT"
BAR_ICON_FONT="-*-siji-*-*-*-*-10-*-*-*-*-*-*-*"
BAR_OPT="-d -f $BAR_FONT -f $BAR_ICON_FONT -g ${BAR_W}x${BAR_H}+${BAR_X}+${BAR_Y} -B $BAR_BG -F $BAR_FG -u 2 -a 30 -r $BW -R `xrq *.color8`"

FIFO_PATH="/tmp/groups.fifo"
test -e "$FIFO_PATH" && rm "$FIFO_PATH"
mkfifo "$FIFO_PATH"

C_ICON=`xrq '*.color6'`
C_NR=`xrq '*.color8'`

# Group status
while true; do
    g_out="G"
    # Check each group
    for gid in $(seq 1 $GNUMBER); do
        # If we find no icon, fall back to group id
        g_icon="$gid"
        # Get the first window in the group, if there's any
        g_window="$(ls -1 /tmp/groaw/$gid | head -n 1)"
        g_name=
        test -n "$g_window" && g_name="$(xprop -id $g_window | grep CLASS | cut -d'=' -f2 | cut -d'"' -f4)"

        # get icon
        case $g_name in
            *Firefox*)
                g_icon=""
                ;;
            *URxvt*|*st*)
                g_icon=""
                ;;
            *Transmission*)
                g_icon=""
                ;;
            imv*)
                g_icon=""
                ;;
            *libreoffice*)
                g_icon=""
                ;;
            *)
                test -z "$g_name" || g_icon=""
                ;;
        esac
        if groaw -p $gid; then
            g_this_out="%{U${BAR_UN}}%{+u} ${g_icon} %{-u}%{U-}"
        else
            g_this_out=" ${g_icon} "
        fi
        if [ "$g_icon" = "$gid" ]; then
            g_this_out="%{F$C_NR}${g_this_out}%{F-}"
        else
            g_this_out="%{F$C_ICON}${g_this_out}%{F-}"
        fi
        g_this_out="%{A1:groaw -t ${gid}:}${g_this_out}%{A}"
        g_out="${g_out}${g_this_out}"
    done
    echo "$g_out"
    sleep 1
done > "$FIFO_PATH" &

cat "$FIFO_PATH" | \
while read -r line; do
    case $line in
        G*)
            echo "%{c}${line#?}"
            ;;
    esac
done | lemonbar $BAR_OPT

