#!/bin/sh

px=`wmp | cut -d' ' -f1`
py=`wmp | cut -d' ' -f2`

for wid in $(lsw | tac); do
	wx=`wattr x $wid`
	wy=`wattr y $wid`

	([ $wx -gt $px ] || [ $wy -gt $py ]) && continue

	ww=`wattr w $wid`
	wh=`wattr h $wid`

	([ $(( wx + ww )) -lt $px ] ||
		[ $(( wy + wh )) -lt $py ]) && continue
	echo $wid
	break
done
