#! /bin/bash
# A little panel that shows the current time in the corner
# (c) tudurom 2016 - wtfpl
#

. wmrc
. panelsrc
. iconsrc

clock() {
  format='%a %d %B %H:%M'
  echo -e "%{c}%{T2}%{F$PANEL_ACCENT_COLOR}$ICON_CLOCK%{T-}%{F-} $(date "+$format")"
}

width=110
height=5
pd_x="$(cat $HOME/.cache/ppd_sizes | cut -d' ' -f1)"
pd_y="$(cat $HOME/.cache/ppd_sizes | cut -d' ' -f2)"
pd_width="$(cat $HOME/.cache/ppd_sizes | cut -d' ' -f3)"
pd_height="$(cat $HOME/.cache/ppd_sizes | cut -d' ' -f4)"

panel_width=$(( width + 2 * GENERAL_GAP ))
panel_height=$(( height + 2 * GENERAL_GAP ))
panel_x=$(( (pd_x + pd_width) - panel_width - GENERAL_GAP ))
panel_y=$(( (pd_y + pd_height) - panel_height - GENERAL_GAP ))
panel_opts="$PANEL_OPTS -g ${panel_width}x${panel_height}+${panel_x}+${panel_y}"

while true; do
  clock
  sleep 1
done | lemonbar $panel_opts
