#! /bin/sh -x
# A little panel that shows the current time in the corner
# (c) tudurom 2016 - wtfpl
#

PANEL_ACCENT_COLOR="$(xrq '*.color9')"
PANEL_BG_COLOR="$(xrq '*background')"
PANEL_FG_COLOR="$(xrq '*.color14')"

clock() {
  format='%a %d %B %H:%M'
  echo "%{c}%{T2}%{F$PANEL_ACCENT_COLOR}%{T-}%{F-} $(date "+$format")"
}

width=110
height=5
pd_x="$(dattr -x $(ppd))"
pd_y="$(dattr -y $(ppd))"
pd_width="$(dattr -w $(ppd))"
pd_height="$(dattr -h $(ppd))"

panel_width=$(( width + 2 * GENERAL_GAP ))
panel_height=$(( height + 2 * GENERAL_GAP ))
panel_x=$(( (pd_x + pd_width) - panel_width - GENERAL_GAP ))
panel_y=$(( (pd_y + pd_height) - panel_height - GENERAL_GAP ))
panel_opts="-d -a 30 -f $PANEL_FONT -f $PANEL_ICON_FONT -B $PANEL_BG_COLOR -F $PANEL_FG_COLOR -g ${panel_width}x${panel_height}+${panel_x}+${panel_y}"

while true; do
  clock
  sleep 1
done | lemonbar $panel_opts
