#! /bin/bash
#
# Little panel to show current playing song
# (c) tudurom 2016 - wtfpl
#

. wmrc
. panelsrc
. iconsrc

last_title="-"
music() {
  if [ $(mpc status | wc -l ) -eq 3 ]; then
    last_title=$(mpc status | head -n 1)
  elif [ $(mpc status | wc -l) -eq 0 ]; then
    last_title="-"
  fi

  if [ -n "$(mpc status | grep paused)" ]; then
    icon="$ICON_PAUSE"
  elif [ -n "$(mpc status | grep playing)" ]; then
    icon="$ICON_PLAY"
  else
    icon="$ICON_STOP"
  fi

  echo -e "%{c}%{A1:mpc toggle:}%{A2:urxvt -e /usr/bin/cava &:}%{A3:mpc stop:}%{A4:mpc next:}%{A5:mpc prev:}%{T2}%{F$PANEL_ACCENT_COLOR}${icon}%{T-}%{F-} $last_title%{A}%{A}%{A}%{A}%{A}"
}

width=330
height=5
root_window=$(lsw -r)
root_width=$(wattr w $root_window)
root_height=$(wattr h $root_window)

panel_width=$(( width + 2 * GENERAL_GAP ))
panel_height=$(( height + 2 * GENERAL_GAP ))
panel_x=$(( root_width - panel_width - GENERAL_GAP ))
panel_y=$(( GENERAL_GAP ))
panel_opts="$PANEL_OPTS -g ${panel_width}x${panel_height}+${panel_x}+${panel_y}"

while true; do
  music
  sleep 1
done | lemonbar $panel_opts | sh
