#!/bin/sh
#
# notifyd - notification daemon
# (c) tudurom 2016 - wtfpl
#

NOTIFY_FIFO_PATH="${NOTIFY_FIFO_PATH:-/tmp/notifyd.fifo}"
NOTIFY_COUNTER_PATH="${NOTIFY_COUNTER_PATH:-/tmp/notifyd.cnt}"

# create fifo
test -p $NOTIFY_FIFO_PATH || mkfifo $NOTIFY_FIFO_PATH
rm "$NOTIFY_COUNTER_PATH"; echo "0" > "$NOTIFY_COUNTER_PATH"

# display vars
DISPLAY_X="$(dattr -x `ppd`)"
DISPLAY_Y="$(dattr -y `ppd`)"
DISPLAY_W="$(dattr -w `ppd`)"
DISPLAY_H="$(dattr -h `ppd`)"

space_len="$(txtw -f "PANEL_FONT_NAME" " ")"
NOTIFY_H="$(( $PANEL_STATUS_HEIGHT ))"
NOTIFY_Y="$(( DISPLAY_Y + GENERAL_GAP ))"

gn() {
    cat "$NOTIFY_COUNTER_PATH"
}

sn() {
    echo "$1" > "$NOTIFY_COUNTER_PATH"
}

sn "0"

tail -f "$NOTIFY_FIFO_PATH" | \
while IFS= read -r message; do
    # increment counter
    sn "$(( $(gn) + 1 ))"

    {
        NOTIFY_W="$(( 4 * space_len + $(txtw -f "$PANEL_FONT_NAME" "$(echo "$message" | tr -cd '[[:alnum:]]._-')")  ))"
        NOTIFY_X="$(( DISPLAY_X + DISPLAY_W - (GENERAL_GAP + NOTIFY_W + 2 * BW) ))"
        NOTIFY_Y="$(( DISPLAY_Y + GENERAL_GAP + ( $(gn) - 1 ) * (NOTIFY_H + GENERAL_GAP) ))"
        popup $NOTIFY_X $NOTIFY_Y $NOTIFY_W $NOTIFY_H "$message"

        # decrement the counter
        sn "$(( $(gn) - 1 ))"
    } &
done
