#!/bin/sh
#
# popup - display popup
# (c) tudurom 2016 - wtfpl
#

POPUP_FONT=${POPUP_FONT:-Metis}
POPUP_DURATION=${POPUP_DURATION:-5}

BAR_X="$1"
BAR_Y="$2"
BAR_W="$3"
BAR_H="$4"
MESSAGE="$5"

BAR_BG=`xrq '*.background'`
BAR_FG=`xrq '*.color14'`
BAR_FONT="$PANEL_FONT"

bar_opts="-g ${BAR_W}x${BAR_H}+${BAR_X}+${BAR_Y} -B${BAR_BG} -F${BAR_FG} -f ${BAR_FONT} -d"

(
  char_len="$(txtw -f "$POPUP_FONT" "#")"
  tx_len="25"
  echo "$MESSAGE" | skroll -r -l -n $tx_len &
  sleep "$POPUP_DURATION" && kill $!
) | lemonbar ${bar_opts}
