#!/bin/sh
#
# popup - display popup
# (c) tudurom 2016 - wtfpl
#

. $HOME/bin/wmrc

POPUP_DURATION=${POPUP_DURATION:-5}

BAR_X="$1"
BAR_Y="$2"
BAR_W="$3"
BAR_H="$4"
MESSAGE="$5"

BAR_BG="$PANEL_BG_COLOR"
BAR_FG=`xrq '*.color14'`
BAR_FONT="$PANEL_FONT"
BAR_ICON_FONT="$PANEL_ICON_FONT"

bar_opts="-g ${BAR_W}x${BAR_H}+${BAR_X}+${BAR_Y} -B${BAR_BG} -F${BAR_FG} -f ${BAR_FONT} -f ${BAR_ICON_FONT} -d -r $PANEL_BORDER_WIDTH -R $PANEL_BORDER_COLOR"

(
echo "%{c}$MESSAGE"
sleep 1.5
) | lemonbar ${bar_opts}
