#!/bin/sh
#
# popup - display popup
# (c) tudurom 2016 - wtfpl
#

POPUP_FONT=${POPUP_FONT:-lemon}
POPUP_DURATION=${POPUP_DURATION:-5}

BAR_X="$1"
BAR_Y="$2"
BAR_W="$3"
BAR_H="$4"
MESSAGE="$5"

BAR_BG="$PANEL_BG_COLOR"
BAR_FG=`xrq '*.color14'`
BAR_FONT="$PANEL_FONT"

bar_opts="-g ${BAR_W}x${BAR_H}+${BAR_X}+${BAR_Y} -B${BAR_BG} -F${BAR_FG} -f ${BAR_FONT} -d -r $BW -R `xrq *.color8`"

(
tx_len="35"
echo "$MESSAGE" | skroll -r -n $tx_len
) | lemonbar ${bar_opts}
