#!/bin/sh
#
# "Simple" status bar
# (c) tudurom 2016 - wtfpl
#

test -z "$DISPLAY" && echo "statusbar needs a working X environment" && exit 1

is_int() {
  case $1 in
    ''|*[!0-9]*) return 1 ;;
    *) return 0 ;;
  esac
}

# Setup {{{

  # Create fifo
  FIFO_PATH=/tmp/status.fifo
  test -e "$FIFO_PATH" && rm "$FIFO_PATH"
  mkfifo "$FIFO_PATH"

  # Color definitions
  C0="$(xrq '*color0')"
  C1="$(xrq '*color1')"
  C2="$(xrq '*color2')"
  C3="$(xrq '*color3')"
  C4="$(xrq '*color4')"
  C5="$(xrq '*color5')"
  C6="$(xrq '*color6')"
  C7="$(xrq '*color7')"
  C8="$(xrq '*color8')"
  C9="$(xrq '*color9')"
  C10="$(xrq '*color10')"
  C11="$(xrq '*color11')"
  C12="$(xrq '*color12')"
  C13="$(xrq '*color13')"
  C14="$(xrq '*color14')"
  C15="$(xrq '*color15')"
  #CF="$(xrq '*foreground')"
  CF="$C6"
  CB="$(xrq '*.background')"
  #CB="#1d2a30"

  PD_X="$(dattr -x $(ppd))"
  PD_Y="$(dattr -y $(ppd))"
  PD_WIDTH="$(dattr -w $(ppd))"
  PD_HEIGHT="$(dattr -h $(ppd))"

  BAR_WIDTH=$(echo "$(dattr -w `ppd`)*0.5" | bc | cut -d'.' -f1)
  BAR_HEIGHT="$PANEL_STATUS_HEIGHT"
  BAR_X="$(echo "($(dattr -w `ppd`) - $BAR_WIDTH) / 2" | bc)"
  BAR_Y="$GENERAL_GAP"
  # BAR_WIDTH="$(dattr -w `ppd`)"
  # BAR_HEIGHT="$PANEL_STATUS_HEIGHT"
  # BAR_X="0"
  # BAR_Y="0"

  SEP_SMALL="        "
  SEP_BIG="            "

  # Number of groups
  GNUMBER=6

  # Bar options
  BAR_OPTS=""
  # Because wmutils
  BAR_OPTS="${BAR_OPTS} -d -b -R $C8 -r 3"
  # Gonna position it centered and respect the gaps
  BAR_OPTS="${BAR_OPTS} -g ${BAR_WIDTH}x${BAR_HEIGHT}+${BAR_X}+${BAR_Y}"
  # Colors
  BAR_OPTS="${BAR_OPTS} -B ${CB} -F ${CF}"
  BAR_OPTS="${BAR_OPTS} -u 2"
  BAR_OPTS="${BAR_OPTS} -f ${PANEL_FONT} -f ${PANEL_ICON_FONT}"

# }}}

# Gather info {{{

  # Current time
  time_format='%a %d %B %H:%M'
  # If it's first of April, show the Epoch time
  test "$(date +"%d %m")" = "01 04" && time_format='%s'
  while true; do
    echo "T%{F$C14}%{F-} $(date +"$time_format")"
    sleep 10
  done > "$FIFO_PATH" &

  # Music
  while true; do
    if [ $(mpc status | wc -l) -eq 3 ]; then
      last_title="$(mpc status | head -n 1)"
    elif [ $(mpc status | wc -l) -eq 0 ]; then
      last_title="-"
    fi

    if [ -n "$(mpc status | grep pause)" ]; then
      icon=""
    elif [ -n "$(mpc status | grep playing)" ]; then
      icon=""
    else
      icon=""
    fi
    echo "M%{A1:mpc toggle:}%{F$C9}${icon}%{F-} ${last_title}%{A}"
    sleep 1
  done > "$FIFO_PATH" &

  # Battery status
  while true; do
    batt_status="$(apm -b)"
    batt_percentage="$(apm -l)"
    # Icons
    if [ "$batt_status" -eq 3 ]; then
      BATT_ICON=""
    elif [ "$batt_status" -eq 0 ]; then
      BATT_ICON=""
    elif [ "$batt_status" -eq 1 ]; then
      BATT_ICON=""
    else
      BATT_ICON=""
    fi
    echo "B%{F$C13}${BATT_ICON}%{F-} ${batt_percentage}"
    sleep 10
  done > "$FIFO_PATH" &

  # Volume
  while true; do
    pcm=$(mixer -S pcm | cut -d':' -f2)
    volume=$(mixer -S vol | cut -d':' -f2)
    if [ "$pcm" -gt 0 ]; then
      if [ $volume -ge 50 ]; then
        vicon=
      else
        vicon=
      fi
    else
      vicon=
    fi
    echo "V%{A3:mute:}%{A4:mixer vol +5:}%{A5:mixer vol -5:}%{F$C12}$vicon%{F-} $volume%{A}%{A}%{A}"
    sleep 0.5
  done > "$FIFO_PATH" &

# }}}

# Process the data and show it {{{

  cat "$FIFO_PATH" | \
  while read -r line; do
    case $line in
      # Time
      T*)
        time="${line#?}"
        ;;
      M*)
        music="${line#?}"
        ;;
      B*)
        batt="${line#?}"
        ;;
      V*)
        vol="${line#?}"
        ;;
      esac
    # Show time!
    echo "%{c}${SEP_BIG}${music}${SEP_SMALL}${vol}${SEP_SMALL}${batt}${SEP_SMALL}${time}${SEP_BIG}"
  done |\
  lemonbar $BAR_OPTS | sh
# }}}

wait

