#!/bin/sh
#
# z3bra - 2014 (c) wtfpl
# modified by tudurom for multimonitor support and fixes
# arrange windows in a tiled pattern

# default values for gaps and master area
PANEL="$(( PANEL_STATUS_HEIGHT ))"
GAP=${GAP:-$GENERAL_GAP}
MASTER=${MASTER:-940}

# get current window id and its borderwidth
PFW=$(pfw)
BW=$(wattr b $PFW)

# get root window's size (beware, multi-head setups...)
SW=$(dattr -w $(pfd))
SH=$(dattr -h $(pfd))
SX=$(dattr -x $(pfd))
SY=$(dattr -y $(pfd))
# The other limits of the monitor
LX=$(( SX + SW ))
LY=$(( SY + SH ))

# Checks if a window is on a display
isonmon() {
  wid="$1"
  window_x="$(wattr x $wid)"
  window_y="$(wattr y $wid)"
  [ "$window_x" -ge "$SX" ] && [ "$window_y" -ge "$SY" ] &&\
  [ "$window_x" -le "$LX" ] && [ "$window_y" -le "$LY" ]
}

# get the number of windows to put in the stacking area
# only consider the windows on the focused monitor
MAX=0
for wid in $(lsw | grep -v $PFW); do
  isonmon $wid && MAX=$(( MAX + 1 ))
done

# calculate usable screen size (without borders and gaps)
SW=$((SW - GAP - 2*BW))
SH=$((SH - GAP - PANEL))

Y=$((0 + GAP + PANEL))
# put current window in master area
wtp $(( SX + GAP )) $(( SY + Y )) $((MASTER - GAP - 2*BW)) $((SH - GAP - 2 * BW)) $PFW

# and now, stack up all remaining windows on the right
X=$(( SX + MASTER + GAP ))
W=$(( SW - MASTER - GAP ))
H=$(( SH / MAX - GAP - 2*BW ))

for wid in $(lsw|grep -v $PFW); do
    window_x="$(wattr x $wid)"
    window_y="$(wattr y $wid)"
    # only move if the window is on the focused monitor
    isonmon $wid && {
      wtp $X $Y $W $H $wid
      Y=$((Y + H + GAP + 2*BW))
    }
done

# vim: set ft=sh :
