#! /bin/dash
#
# handle wew events
# (c) tudurom 2016 - wtfpl
#

BLUR="$HOME/.blur.png"
WALL="$HOME/wallpapers/trees.jpg"

while IFS=: read ev wid; do
  #sleep 0.1
  case $ev in
    # Window creation
    16)
      if ! wattr o $wid; then
        cornerw md $wid
      fi
      ;;

    # Mapping request aka group activated
    19)
      if ! wattr o $wid; then
        focusw $wid
        test $(lsw | wc -l) -eq 1 && hsetroot -fill $BLUR
      fi
      ;;

    # Window closed
    18)
      if ! wattr $(pfw); then
        focusw $(closestw prev)
        test -z "$(lsw)" && hsetroot -fill $WALL
      fi
      ;;
  esac
done
