#! /bin/sh
#
# handle wew events
# (c) tudurom 2016 - wtfpl
#

while IFS=: read ev wid; do
  #sleep 0.1
  case $ev in
    # Window creation
    16)
      if ! wattr o $wid; then
        cornerw md $wid
      fi
      ;;

    # Mapping request aka group activated
    19)
      if ! wattr o $wid; then
        focusw $wid
      fi
      ;;

    # Window closed
    18)
      if ! wattr $(pfw); then
        focusw $(closestw prev)
      fi
      ;;
  esac
done
