#! /bin/sh
#
# handle wew events
# (c) tudurom 2016 - wtfpl
#

while IFS=: read ev wid; do
  #sleep 0.1
  case $ev in
    # Window open
    16)
      wattr o "$wid" || {
        cornerw md "$wid" && focusw "$wid"
      }
      ;;
    # Window closed / unmapped (aka minimized)
    17|18)
      wattr o "$wid" || {
        focusw "$(closestw prev)"
      }
      ;;
    # Window mapped
    19)
      wattr o  $wid || {
        focusw "$wid"
      }
      ;;
  esac
done
