#! /bin/sh

sxhkd &

if [ -e "$BSPWM_STATE" ]; then
  bspc wm -l "$BSPWM_STATE"
  rm "$BSPWM_STATE"
fi

bspc config window_gap          0
bspc config border_width        2

bspc config split_ratio         0.50
bspc config borderless_monocle  false
bspc config gapless_monocle     false
bspc config focus_by_distance   true

bspc config normal_border_color "#273941"
#bspc config focused_border_color "#71c2af"
bspc config focused_border_color "#273941"


if [ $(bspc query -M | wc -l) -eq 2 ]; then
  bspc monitor LVDS-0 -d 4 5 6
  bspc monitor $(bspc query -M | grep -v "LVDS-0" | head -n 1) -d 1 2 3
else
  bspc monitor -d 1 2 3 4 5 6
fi


panel &
setwall &
xsetroot -cursor_name left_ptr &
notifyd &
