#! /bin/sh

sxhkd &

if [ -e "$BSPWM_STATE" ]; then
  bspc wm -l "$BSPWM_STATE"
  rm "$BSPWM_STATE"
fi

bspc config window_gap          0
bspc config border_width        2

bspc config split_ratio         0.50
bspc config borderless_monocle  false
bspc config gapless_monocle     false
bspc config focus_by_distance   true

bspc config normal_border_color "#373e4d"
bspc config focused_border_color "#96b5b4"

if [ $(bspc query -M | wc -l) -eq 2 ]; then
  bspc monitor LVDS-0 -d 6 7 8 9 10
  bspc monitor DP-3 -d 1 2 3 4 5
else
  bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi


panel &
setwall &
xsetroot -cursor_name left_ptr &
