#! /bin/sh

sxhkd &

bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  false
bspc config gapless_monocle     false
bspc config focus_by_distance   true
bspc config focus_follows_pointer true

bspc config normal_border_color "#2b303b"
bspc config focused_border_color "#96b5b4"

if [ $(bspc query -M | wc -l) -eq w ]; then
  bspc monitor LVDS-1 -d 6 7 8 9 10
  bspc monitor DP-3 -d 1 2 3 4 5
else
  bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

panel &
setwall &
xsetroot -cursor_name left_ptr &
