#!/bin/sh

xfce4-volumed-pulse &
compton -b
feh --bg-fill ~/wallpapers/street.png
pkill -f dunst && start-dunst &
/usr/lib/kdeconnectd &
polybar clock &
plank &
lastplayer -h &
(sleep 10 && plasma-browser-integration-host) &
$HOME/.xinitrc -o &
