#!/bin/sh

xfce4-volumed-pulse &
compton -b
feh --bg-fill ~/wallpapers/street.png
pkill -f dunst && start-dunst &
/usr/lib/kdeconnectd &
jgmenu --hide-on-startup 0 &
polybar clock &
plank &
lastplayer -h &
plasma-browser-integration-host &
$HOME/.xinitrc -o &
