---
- name: Check if nix is installer
  ansible.builtin.stat:
    path: /nix
  register: nix_installer_nix_stat

- name: Install Nix
  when: 'not nix_installer_nix_stat.stat.exists'
  block:
    - name: Download Nix installer
      ansible.builtin.get_url:
        url: 'https://install.determinate.systems/nix/nix-installer-{{ ansible_architecture }}-linux'
        dest: '/tmp/nix-installer'
        mode: '0755'
    - name: Run Nix installer
      become: true
      changed_when: true
      ansible.builtin.command:
        cmd: '/tmp/nix-installer install --explain --no-confirm'
