#!/usr/bin/bash

STATUS="$(playerctl status)"
MUSIC="$(playerctl metadata artist) - $(playerctl metadata title)"

declare -A val
val["Playing"]=""
val["Paused"]=""

if [ $? -ne 0 ] || [[ $STATUS = "Stopped" ]]
then
  #echo "No music playing"
  exit 0
else
  echo "${val["$STATUS"]} $MUSIC"
fi

case $BLOCK_BUTTON in
  1) playerctl play-pause & ;;
  3) playerctl stop & ;;
  4) playerctl next & ;;
  5) playerctl previous & ;;
esac &

