name: Flake Check

on:
  pull_request:
  push:
    branches: [master]

jobs:
  flake-check:
    runs-on: nix
    steps:
      - uses: actions/checkout@v3
      - name: Run flake check
        run: nix flake check -L --show-trace
