name: pre-commit

env:
  RUNNER_ARCH: X64

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Setup Nix caching
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run pre-commit hooks on all files
        run: nix develop -c pre-commit run -a
