#!/bin/sh

bspc config border_width          $BW
bspc config window_gap            $GENERAL_GAP

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config top_padding           $(( 2 * BW + PANEL_STATUS_HEIGHT + GENERAL_GAP ))
bspc config focus_follows_pointer true

bspc config normal_border_color   $(xrq '*.color8')
bspc config active_border_color   $(xrq '*.color8')
bspc config focused_border_color  $(xrq '*.color6')
bspc config presel_feedback_color $(xrq '*.color3')

for monitor in $(bspc query -M); do
    bspc monitor $monitor -d A B C D
done

bspc rule -a chromium  desktop=^2
bspc rule -a Firefox   desktop=^2
bspc rule -a qutebrowser desktop=^2
bspc rule -a mpv       state=floating

wmname LG3D
