---
- name: Install packages
  become: true
  community.general.rpm_ostree_pkg:
    name:
      - swaylock # for PAM config to be installed
      - polkit-gnome
    state: present

- name: Install sway Wayland session
  block:
    - name: Create wayland-sessions dir
      become: true
      ansible.builtin.file:
        path: /usr/local/share/wayland-sessions
        state: directory
        mode: "0755"

    - name: Copy session file
      become: true
      ansible.builtin.copy:
        src: sway.desktop
        dest: /usr/local/share/wayland-sessions/sway.desktop
        mode: "0444"
