# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

let
  sources = import ../../nix/sources.nix;
in {
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
      "${sources.nixos-hardware}/lenovo/thinkpad/t440s"
      "${sources.nixos-hardware}/common/pc/ssd"
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" "aes_x86_64" "aesni_intel" "cryptd" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.kernelParams = [ "mitigations=off" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices = {
    enc = {
      device = "/dev/disk/by-uuid/88fd5ba0-450c-474d-9bfe-0423e8e47ef2";
      preLVM = true;
      allowDiscards = true;
    };
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3832ee48-b791-4568-9e28-49cd931e3d49";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd" "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/3832ee48-b791-4568-9e28-49cd931e3d49";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd" "noatime" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/3832ee48-b791-4568-9e28-49cd931e3d49";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd" "noatime" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/3832ee48-b791-4568-9e28-49cd931e3d49";
      fsType = "btrfs";
      neededForBoot = true;
      options = [ "subvol=log" "compress=zstd" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/AF61-0AAB";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/5c429c43-50ee-49ec-9fb4-a3e087349943"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "schedutil";
}
