set -sg escape-time 0

setw -g mode-key vi
set -g status-keys vi

bind h split-window -v
bind v split-window -h

set -g default-command "/usr/bin/env fish"

# set -as terminal-features 'xterm-ghostty*:256:clipboard:ccolour:cstyle:extkeys:focus:hyperlinks:mouse:osc7:RGB:sixel:title'
set -g mouse on
