#!/bin/sh

foc="$(xrq '*.color12' | sed 's/\#/0x/')"
unfoc="$(xrq '*.color8' | sed 's/\#/0x/')"

waitron wm_config border_width $BW
waitron wm_config color_focused $foc
waitron wm_config color_unfocused $unfoc
waitron wm_config gap_width all $GENERAL_GAP
waitron wm_config gap_width top $(( 2 * GENERAL_GAP + PANEL_STATUS_HEIGHT ))
waitron wm_config grid_gap_width 10
waitron wm_config cursor_position middle
waitron wm_config groups_nr $GNUMBER
waitron wm_config enable_sloppy_focus true
