#!/bin/sh

. $HOME/bin/wmrc

foc="$(echo "$BORDER_COLOR_FOC" | sed 's/\#/0x/')"
unfoc="$(echo "$BORDER_COLOR_UNFOC" | sed 's/\#/0x/')"

waitron wm_config border_width $BW
waitron wm_config color_focused $foc
waitron wm_config color_unfocused $unfoc
waitron wm_config gap_width all $GENERAL_GAP
waitron wm_config gap_width top $(( (GENERAL_GAP + BW) + PANEL_STATUS_HEIGHT ))
waitron wm_config grid_gap_width 10
waitron wm_config cursor_position middle
waitron wm_config groups_nr $GNUMBER
waitron wm_config enable_sloppy_focus false
waitron wm_config sticky_windows false
waitron wm_config enable_borders true

pgrep last_focus_watcher > /dev/null 2>&1 || last_focus_watcher.sh &
