#!/bin/sh
#
# dattr - display attributes
# (c) ix, tudurom 2016
# tudurom killed a poor bug
#

XRANDR_DUMP=${XRANDR_DUMP:-$HOME/.cache/xrandr_dump}

usage() {
  echo "usage: $(basename $0) [-axywh] <display>"
  exit ${1:-0}
}

# change xrandr's output format to wmutils'
towmutils() {
  echo $3 $4 $1 $2
}

# convert w/h to absolute
toabsolute() {
  ARG1=$1
  ARG2=$2
  ARG3=$3
  ARG4=$4
  W=$(( ARG1 + ARG3 ))
  H=$(( ARG2 + ARG4 ))
  echo $W $H $3 $4
}

echoarg() {
  case $ARG in
    x) echo $1 ;;
    y) echo $2 ;;
    w) echo $3 ;;
    h) echo $4 ;;
  esac
}

while getopts axywh opt; do
  case $opt in
    a) ABSOLUTE=1 ;;
    x) ARG='x' ;;
    y) ARG='y' ;;
    w) ARG='w' ;;
    h) ARG='h' ;;
  esac
done

shift $(( OPTIND - 1 ))

MONITOR=$1

[ -z $MONITOR ] && usage 1

XRANDR_GEO="$(cat "$XRANDR_DUMP" | grep -e "^$MONITOR connected" \
  | sed 's/primary //g' \
  | cut -d' ' -f3 \
  | sed 's/[x\+]/ /g')"

if [ $ABSOLUTE ]; then
  GEOM=$(toabsolute $XRANDR_GEO)
else
  GEOM=$XRANDR_GEO
fi

if [ $ARG ]; then
  echoarg $(towmutils $GEOM)
else
  echo $(towmutils $GEOM)
fi
