#!/bin/sh
#
# lsd - list the current displays
# (c) ix, tudurom 2016
# modified by tudurom to show only currently used displays
#

xrandr | grep -e "^.* connected" | \
while read -r MONITOR; do
  test1="$(echo $MONITOR | cut -d' ' -f3 | cut -c1-1)"
  test2="$(echo $MONITOR | cut -d' ' -f4 | cut -c1-1)"
  if [ "$test1" -eq "$test1" ] 2>/dev/null || [ "$test2" -eq "$test2" ] 2>/dev/null; then
    echo "$MONITOR" | cut -d' ' -f1
  fi
done
