#!/usr/bin/bash

. $HOME/.scripts/colors

barheight=24
monitor=0
mgeom=( $(herbstclient monitor_rect "$monitor") )
geom="${mgeom[2]}x$barheight+0+0"
basefont="M+ 1p"
iconfont="FontAwesome"

herbstclient pad $monitor $(expr $barheight)

~/.scripts/desktop/panel/panel.rb | lemonbar -B "$BAR_BG_COLOR" -F "$TEXT_COLOR" -f "$basefont" -f "$basefont:Bold" -f "$iconfont" -g $geom -a 20| sh
