#!/usr/bin/bash

. $HOME/.scripts/colors

barheight=30
monitor=0
mgeom=( $(herbstclient monitor_rect "$monitor") )
geom="${mgeom[2]}x$barheight+0+0"
basefont="-*-tamzen-medium-*-*-*-17-*-*-*-*-*-*-*"
boldfont="-*-tamzen-bold-*-*-*-17-*-*-*-*-*-*-*"
iconfont="-misc-tamsynmod-medium-r-normal--17-123-100-100-c-80-iso8859-1"

herbstclient pad $monitor $(expr $barheight)

~/.scripts/desktop/panel/panel.rb | lemonbar -B "$BAR_BG_COLOR" -F "$TEXT_COLOR" -f "$basefont" -f "$boldfont" -f "$iconfont" -g $geom -a 20| sh
