#!/bin/sh
# Uses xwinwrap to display given animated .gif in the center of the screen

if [ $# -ne 1 ]; then
    echo 1>&2 Usage: $0 image.gif
    exit 1
fi

#get screen resolution
#SCRH=`xrandr | awk '/current/ { print $8 }'`
#SCRW=`xrandr | awk '/current/ { print $10 }'`
#SCRW=${SCRW%\,}
SCRH=$(xrandr  | grep \* | cut -d' ' -f4 | head -n 2 | tail -n 1 | awk -F "x" '{ print $2 }')
SCRW=$(xrandr  | grep \* | cut -d' ' -f4 | head -n 2 | tail -n 1 | awk -F "x" '{ print $1 }')

#get gif resolution
IMGHW=`gifsicle --info $1 | awk '/logical/ { print $3 }'`
IMGH=${IMGHW%x*}
IMGW=${IMGHW#*x}

#calculate position
#POSH=$((($SCRH/2)-($IMGH/2)))
#POSW=$((($SCRW/2)-($IMGW/2)))
POSH=0
POSW=0

xwinwrap -g ${IMGHW}+${POSH}+${POSW} -ov -ni -s -nf -- gifview -w WID $1 -a
