#!/bin/sh

. $HOME/bin/wmrc

no="$1"

curr="$(mpc status)"

status="$(echo "$curr" | sed -n 2p | tr -d '[]' | cut -d' ' -f1)"
ico=""
if [ "$status" = "playing" ]; then
	ico=""
elif [ "$status" = "paused" ]; then
	ico=""
else
	ico=""
fi
song="$(mpc current)"

out="%{F$PANEL_ACCENT_COLOR}${ico}%{F-} ${song}"
if [ "$no" = "col" ]; then
	out="${ico} ${song}"
elif [ "$no" = "ico" ]; then
	out="${song}"
fi

echo "$out"
