#! /bin/sh
#
# nioup - Simple scripts to upload files to the iotek pastebin
# (c) tudurom - 2016 (wtfpl)
#

test $# -ne 1 && {
  echo "Usage: $(basename "$0") <file to paste>"
  exit 1
}

curl -sLT- p.iotek.org < "$1"
