#!/bin/sh

dir="$HOME/usr/work/problems"
template="template.c"

if [ $# -lt 1  ]; then
    printf "Project name? "
    read proj_name
    printf "\n"
else
    proj_name=$1
fi

project_dir="${dir}/${proj_name}"

test -d "$project_dir" && echo "Already exists." && exit 1

echo "$(tput bold)"
mkdir -p $project_dir
echo "$(tput setaf 2)created $project_dir"
touch "${project_dir}/${proj_name}.in"
echo "$(tput setaf 2)created ${project_dir}/${proj_name}.in"
touch "${project_dir}/${proj_name}.out"
echo "$(tput setaf 2)created ${project_dir}/${proj_name}.out"
cp "${dir}/${template}" "${project_dir}/${proj_name}.c"
echo "$(tput setaf 2)created ${project_dir}/${proj_name}.c"
echo "$(tput sgr0)"

