#! /bin/sh

LAPTOP_SCREEN="$(lsd | grep "LVDS-*[0-9]")"

single_ext="on"
ext_monitor=$(lsd | grep -v "$LAPTOP_SCREEN" | tail -n 1)
if [ -z "$ext_monitor" ]; then
  xrandr --output "$LAPTOP_SCREEN" --primary
else
  xrandr --output "$ext_monitor" --auto --left-of "$LAPTOP_SCREEN" --primary
  if [ $single_ext = "on" ]; then
    xrandr --output "$LAPTOP_SCREEN" --off
  fi
fi
