#! /bin/bash

LAPTOP_SCREEN="LVDS-1"

single_ext="on"
ext_monitor=$(xrandr | grep " connected" | grep -v "$LAPTOP_SCREEN" | awk '{print $1}')
if [[ $ext_monitor == "" ]]; then
  xrandr --output "$LAPTOP_SCREEN" --primary
else
  xrandr --output "$ext_monitor" --auto --left-of "$LAPTOP_SCREEN" --primary
  bspc config -m "$LAPTOP_SCREEN" top_padding 0
  if [[ $single_ext == "on" ]]; then
    xrandr --output "$LAPTOP_SCREEN" --off
  fi
fi
