#! /bin/sh

LAPTOP_SCREEN="$(xrandr | grep "LVDS-*[0-9]" | cut -d' ' -f1)"

single_ext="off"
ext_monitor=$(xrandr | grep " connected" | grep -v "$LAPTOP_SCREEN" | awk '{print $1}')
if [ $ext_monitor = "" ]; then
  xrandr --output "$LAPTOP_SCREEN" --primary
else
  xrandr --output "$ext_monitor" --auto --left-of "$LAPTOP_SCREEN" --primary
  if [ $single_ext = "on" ]; then
    xrandr --output "$LAPTOP_SCREEN" --off
  fi
fi
