#! /usr/bin/python
import os
import time
import random

donger = os.environ.get('DONGER', 0)
surprise = os.environ.get('SNOWDEN', 0)
custom = os.environ.get('CUSTOM', 0)

date = time.strftime('%d/%m')
rnd = random.randrange(1, 101)

if donger or date == '01/04':
    os.system('hsetroot -fill ~/wallpapers/april_wall.png')
elif surprise or rnd == 2:
    os.system('hsetroot -fill ~/wallpapers/snowden.jpg')
elif custom:
    os.system('hsetroot -fill %s' % custom)
else:
    os.system('hsetroot -fill ~/wallpapers/trees.jpg')
    os.system('convert ~/wallpapers/trees.jpg -blur 0x8 ~/.blur.png')

