#!/bin/sh
#
# todo - simple todo script
# mod of xero's by arc
# modified even more by tudurom
#

file="$HOME/.todo"
if [ -z $1 ] ; then
  echo "┌──────[ todo ]──[ version 0.0.2 ]─────── ─ ─"
  echo "│ usage: todo <options>"
  echo "│ author: xero, arc and tudurom"
  echo "├────────────────[ options ]"───────────── ─ ─
  echo "│ -s          display the todo list"
  echo "│ -a <string> add a todo item"
  echo "│ -d <number> delete a todo item"
  echo "└──────────────────────────────────────── ─ ─"
elif [ "$1" = '-s' ]; then
  while true;
  do
    clear
    tput setaf 2
    echo ""
    echo "     ██                 ██"
    echo "    ░██                ░██"
    echo "   ██████  ██████   ██████  ██████"
    echo "  ░░░██  ░██░░░░██░██░░░██░██   ░██"
    echo "    ░██  ░██   ░██░██  ░██░██   ░██"
    echo "    ░░██ ░░██████ ░░██████░░██████"
    echo "     ░░   ░░░░░░   ░░░░░░  ░░░░░░"
    echo ""
    tput bold
    tput setaf 0
    echo "     _ __ __________________ __ _"
    echo ""
    tput sgr0
    nl -b a $file
    sleep 4
  done
elif [ "$1" = '-d' ]; then
  if [ -z "$2" ]; then
    echo "missing option"
    echo "pass an item number to delete"
  else
      new="$(sed "${2}d" $file)"
      echo "$new" | tee "$file"
      unset new
  fi
elif [ "$1" = '-a' ]; then
  shift
  if [ -z "$@" ]; then
    echo "missing option"
    echo "pass an item to add"
  else
    echo "$@" >> $file
  fi
else
  echo "unknown option"
  echo "call 'todo --help' for more info"
fi
