#!/bin/sh
# Reads list of urls, shows them in a nice menu and then opens the selected url
# (c) tudurom 2016 - wtfpl
#

monitor_width="$(dattr -w $(ppd))"
font="-benis-lemon-medium-r-normal--10-110-75-75-m-50-*"

while read -r line; do
  echo "$line"
done | dmenu | xargs xdg-open

# vim: set ft=sh :
