#! /bin/dash
#
# Set wallpaper
# (c) tudurom 2016 - wtfpl
#

DEFAULT_WALL="$HOME/wallpapers/lost_dcat.jpg"
APRIL_WALL="$HOME/wallpapers/april_wall.png"

if [ "$(date +"%d/%m")" = "01/04" ]; then
  hsetroot -fill "$APRIL_WALL"
elif [ $# -ge 1 ]; then
  option="fill"
  test -n $2 && option="$2"
  hsetroot -${option} $1
else
  hsetroot -fill $DEFAULT_WALL
fi

# vim: set ft=sh :
