#!/bin/sh

c_name="$1"
c_author="$2"

xrdb -merge "$3"

a="$(cat <<END
metadata:
  name: $c_name
  author: $c_author
colors:
  bg: "$(xrq '*.background')"
  fg: "$(xrq '*.foreground')"
  cr: "$(xrq '*.foreground')"

  00: "$(xrq '*.color0')"
  08: "$(xrq '*.color8')"

  01: "$(xrq '*.color1')"
  09: "$(xrq '*.color9')"

  02: "$(xrq '*.color2')"
  10: "$(xrq '*.color10')"

  03: "$(xrq '*.color3')"
  11: "$(xrq '*.color11')"

  04: "$(xrq '*.color4')"
  12: "$(xrq '*.color12')"

  05: "$(xrq '*.color5')"
  13: "$(xrq '*.color13')"

  06: "$(xrq '*.color6')"
  14: "$(xrq '*.color14')"

  07: "$(xrq '*.color7')"
  15: "$(xrq '*.color15')"
END
)"

echo "$a"
