---
- name: Get package facts
  ansible.builtin.package_facts:

- name: Install hardware codecs
  become: true
  community.general.rpm_ostree_pkg:
    name: intel-media-driver
    state: present

- name: Install software codecs
  become: true
  when: '"ffmpeg" not in ansible_facts.packages'
  changed_when: true
  ansible.builtin.command: >-
    /usr/bin/rpm-ostree override
      remove
        mesa-va-drivers
        libavcodec-free
        libavfilter-free
        libavformat-free
        libavutil-free
        libpostproc-free
        libswresample-free
        libswscale-free

      --install ffmpeg
      --install mesa-va-drivers-freeworld
