#!/bin/bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# Sets the wallpaper (.scripts/setwall)
CUSTOM=Pictures/timessquare.jpg setwall

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

hc set default_frame_layout 3

hc keybind $Mod-Shift-e quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-q close_and_remove
hc keybind $Mod-Return spawn urxvt
hc keybind $Mod-d spawn $HOME/.scripts/desktop/launch
hc keybind $Mod-Shift-x spawn $HOME/.scripts/lock.sh

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# media keys
MIXER="pulse"
SCONTROL="$(amixer -D $MIXER scontrols | sed -n "s/Simple mixer control '\([A-Za-z ]*\)',0/\1/p" | head -n1 )"
STEP="${1:-5%}"

hc keybind XF86AudioPlay spawn playerctl play-pause
hc keybind XF86AudioNext spawn playerctl next
hc keybind XF86AudioPrev spawn playerctl previous
hc keybind XF86AudioStop spawn playerctl stop
hc keybind XF86AudioRaiseVolume spawn amixer -q -D $MIXER sset $SCONTROL $(capability) ${STEP}+ unmute
hc keybind XF86AudioLowerVolume spawn amixer -q -D $MIXER sset $SCONTROL $(capability) ${STEP}- unmute
hc keybind XF86AudioMute spawn amixer -q -D $MIXER sset $SCONTROL $(capability) toggle

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..10} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
source $HOME/.config/herbstluftwm/colors

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color "$BG_COLOR"
hc set frame_border_normal_color "$INACTIVE_BG_COLOR"
hc set frame_bg_normal_color "$INACTIVE_BG_COLOR"
hc set frame_bg_active_color "$BG_COLOR"
hc set frame_border_width 0
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set window_gap 10

hc attr theme.active.color "$(hc get frame_bg_active_color)"
hc attr theme.normal.color "$(hc get frame_bg_normal_color)"
hc attr theme.urgent.color "$URGENT_BG_COLOR"
hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#18242C'

hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
#hc rule focus=on # normally focus new clients
hc rule focus=on # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors



#find the panel
#panel=~/.config/herbstluftwm/panel.sh
if pgrep panel
then
  kill $(pgrep panel)
fi
panel=~/.scripts/desktop/panel/panel
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
"$panel" &
#for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
#      start it on each monitor
#     "$panel" $monitor &
#done
