#!/usr/bin/env bash

# this is a simple config for herbstluftwm

# Color definitions {{{
C0="$(xrq '*color0')"
C1="$(xrq '*color1')"
C2="$(xrq '*color2')"
C3="$(xrq '*color3')"
C4="$(xrq '*color4')"
C5="$(xrq '*color5')"
C6="$(xrq '*color6')"
C7="$(xrq '*color7')"
C8="$(xrq '*color8')"
C9="$(xrq '*color9')"
C10="$(xrq '*color10')"
C11="$(xrq '*color11')"
C12="$(xrq '*color12')"
C13="$(xrq '*color13')"
C14="$(xrq '*color14')"
C15="$(xrq '*color15')"
CFG="$(xrq '*foreground')"
CBG="$(xrq '*.background')"
# }}}

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# tags
tag_names=( {1..6} )
tag_keys=( {1..6} )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
done

Mod=Mod4
# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color $C8
hc set frame_border_normal_color $C0
hc set frame_bg_normal_color $C8
hc set frame_bg_active_color $C6
hc set frame_border_width 0
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 5
hc set frame_gap $GENERAL_GAP

hc attr theme.active.color $C6
hc attr theme.normal.color $C8
hc attr theme.urgent.color $C9
hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.border_width $BW
hc attr theme.floating.border_width $BW
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color $CBG

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0
hc pad 0 $(( 2 * BW + PANEL_STATUS_HEIGHT + 2 * GENERAL_GAP )) 0 0 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors
